# Generated by Django 5.0.7 on 2024-07-11 12:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_dni', models.IntegerField(max_length=50)),
                ('creation_date', models.DateField(default=datetime.datetime(2024, 7, 11, 12, 41, 21, 45935))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.tipocliente')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
