# Generated by Django 5.0.7 on 2024-07-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 11, 12, 41, 44, 835439)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_dni',
            field=models.IntegerField(),
        ),
    ]
